name: Build for macOS
description: 'Build V8 for macOS'

inputs:
  archive-name:
    description: 'Base name of the archive to create'
    default: v8_macOS
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore CCache
      uses: actions/cache@v4
      with:
        path: .ccache
        key: ${{ runner.os }}-${{ runner.arch }}:libv8:ccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}:libv8:ccache:

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' # https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/refs/heads/main/README.md

    - name: Setup Build Tools
      shell: bash
      run: |
        brew install ccache

        echo "$(brew --prefix ccache)/libexec" >> "$GITHUB_PATH"
        echo "CCACHE_CPP2=yes" >> "$GITHUB_ENV"
        echo "CCACHE_SLOPPINESS=time_macros" >> "$GITHUB_ENV"

        ccacheDir="${GITHUB_WORKSPACE}/.ccache"
        test -d "$ccacheDir" || mkdir "$ccacheDir"

        echo "CCACHE_DIR=$ccacheDir" >> "$GITHUB_ENV"

        if ! command -v xcversion >/dev/null 2>&1; then
          gem install xcode-install
        fi

        xcversion install 15.2

    - name: Download V8 Source
      shell: bash
      run: ./v8_download.sh

    - name: Show Installed SDKs
      shell: bash
      run: xcodebuild -showsdks

    - name: Compile V8
      shell: bash
      run: ./v8_compile.sh

    - name: Show CCache Status
      shell: bash
      run: ccache -s

    - name: Test V8
      shell: bash
      run: ./v8_test.sh

    - name: Archive V8
      shell: bash
      run: ./archive.sh ${{ inputs.archive-name }}
