name: Build for Windows
description: 'Build V8 for Windows'

inputs:
  arch:
    description: 'Architecture to build for'
    default: x64
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore SCCache
      uses: actions/cache@v4
      with:
        path: .sccache
        key: ${{ runner.os }}-${{ inputs.arch }}:libv8:sccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.arch }}:libv8:sccache:

    - name: Setup Scoop
      uses: MinoruSekine/setup-scoop@v4

    - name: Setup Build Tools
      shell: pwsh
      run: |
        scoop install sccache

        $sccacheDir = "$Env:GITHUB_WORKSPACE`\.sccache"
        New-Item -Path "$sccacheDir" -ItemType Directory -Force

        Write-Output "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8 -Append

        $arch = "${{ inputs.arch }}"

        # Map architecture names to MSVC Developer Command Prompt architecture values
        $devcmdArch = switch ($arch) {
          "x64"   { "amd64" }
          "x86"   { "amd64_x86" }
          "arm64" { "amd64_arm64" }
          default {
            Write-Error "Unsupported architecture: $arch"
            exit 1
          }
        }

        Write-Output "DEVCMD_ARCH=$devcmdArch" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8 -Append

    - name: Download V8 Source
      shell: cmd
      run: .\v8_download.bat

    - name: Compile V8
      shell: cmd
      run: .\v8_compile.bat ${{ inputs.arch }}

    - name: Show SCCache Status
      shell: pwsh
      run: sccache --show-stats

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ env.DEVCMD_ARCH }}

    - name: Test V8
      shell: cmd
      run: .\v8_test.bat ${{ inputs.arch }}

    - name: Archive V8
      shell: pwsh
      run: .\archive.bat ${{ inputs.arch }}
