name: Build for Windows
description: 'Build V8 for Windows'

inputs:
  archive-name:
    description: 'Base name of the archive to create'
    default: v8_Windows
    required: false
    type: string
  arch:
    description: 'Architecture to build for'
    default: x64
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore SCCache
      uses: actions/cache@v4
      with:
        path: .sccache
        key: ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:

    - name: Setup Scoop
      uses: MinoruSekine/setup-scoop@v4

    - name: Setup Build Tools
      shell: pwsh
      run: |
        scoop install sccache

        $sccacheDir = "$Env:GITHUB_WORKSPACE`\.sccache"
        New-Item -Path "$sccacheDir" -ItemType Directory -Force

        Write-Output "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8

    - name: Download V8 Source
      shell: cmd
      run: .\v8_download.bat

    - name: Compile V8
      shell: cmd
      run: .\v8_compile.bat ${{ inputs.arch }}

    - name: Show SCCache Status
      shell: pwsh
      run: sccache --show-stats

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Test V8
      shell: cmd
      run: .\v8_test.bat ${{ inputs.arch }}

    - name: Archive V8
      shell: pwsh
      run: .\archive.bat ${{ inputs.archive-name }}
